### ISSUE TITLE
Upgrade majifix legacy API to use latest majifix-jurisdiction

### ISSUE THREAD

**Issue by lykmapipo** [CodeTanzania/majifix-jurisdiction#2]
## Tasks
- [ ] Drop domain field
- [ ] Drop domain index
- [ ] Update UI to use website field
- [ ] Drop location field indexes
- [ ] Drop location field indexes
- [ ] Update UI to allow filling location x,y points
- [ ] Drop boundaries field indexes
- [ ] Drop boundaries field indexes
- [ ] Update UI to allow filling boundaries MultiPolygon points
